language: csharp
solution: NameValueType.sln

matrix:
  include:
    - dotnet: 2.0.0
      mono: none
      dist: trusty     
      script:
        - cd NameValueType
        - dotnet restore
        - dotnet build -c Release