language: csharp
solution: NameValueType.sln

matrix:
  include:
    - dotnet: 2.0.0
      mono: none
      dist: trusty
      env: DOTNETCORE=2  # optional, can be used to take different code paths in your script
      script:
        - dotnet restore
        - dotnet build -c Release
    - mono: latest